### ISSUE TITLE
Make an ARM image available

### ISSUE THREAD

**Issue by Adafede** [Bioconductor/bioconductor_docker#64]
Hi, would be very cool to have an ARM version also available on DockerHub. 

Probably feasible directly within a slightly modified GitHub action.😺

Best,

**Comment by almahmoud** [comment]
Hello. I am assuming you are looking to run on an M1 mac. While we have very recently started supporting arm binaries for Bioconductor packages, it will take some time to provide arm versions of everything in our stack. Unfortunately, it's not as easy as a slightly modified GHA. Two issues we particularly have our eyes on are the one tracking the rocker base image we use (https://github.com/rocker-org/rocker-versioned2/issues/144) as well the GHA support for M1 (https://github.com/actions/runner-images/issues/2187).

**Comment by almahmoud** [comment]
@Adafede I am happy to inform you that an arm64 image is now available in the Github Container registry at `bioconductor/bioconductor:release_3_16` (with special thanks to @martin-g ). It will be pushed to Dockerhub shortly, but feel free to start using it from the github registry and let us know if you encounter any issues!

**Comment by Adafede** [comment]
Hey @almahmoud, just gave it a try and it's working! Thank you very much

**Comment by martin-g** [comment]
Awesome! 🎆

**Comment by almahmoud** [comment]
@Adafede I believe that is due to the fact that it's trying to use the binary repo, which is built with the `amd64` image. We haven't updated `BiocManager::install` yet to account for the multi-platform container images as this one is still in its infancy.
You can avoid using the binaries in the `arm64`-based image by setting the env variable `BIOCONDUCTOR_USE_CONTAINER_REPOSITORY=FALSE`

**Comment by Adafede** [comment]
Indeed, thank you!

**Comment by almahmoud** [comment]
Closing this issue as arm64 image is out there on both GHCR and Dockerhub now
