### ISSUE TITLE
Incorrect references to `rockerdev` Rocker organization in release process document

### ISSUE THREAD

**Issue by noamross** [Bioconductor/bioconductor_docker#72]
Under https://github.com/Bioconductor/bioconductor_docker/blob/master/docs/release_process.md, there are a few references to the `rockerdev` Rocker organization and images.  `rockerdev` was a brief-lived experimental namespace. With Docker Hub ending free support for team organizations, we expect to shut it down. (`rocker/` should continue under Docker's open-source project support.) 

I'm not sure if these are just mistaken documentation or something actually uses images from `rockerdev/`, but they haven't been updated in 3 years and anything that uses them should switch to the main `rocker/` repository.

**Comment by almahmoud** [comment]
The documentation has not been updated but we are using the latest containers. The repository is currently in my focus as I am updating everything before 3.17 release so I will update the documentation as well. In the meantime if you need help with something specific please let us know. Otherwise I will close this issue as the documentation update is already on the TODO list.
